CREATE SEQUENCE seq_utilisateur_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_compte_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_notification_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
